NettyByteBufPool.numDirectArenas=5
NettyByteBufPool.numHeapArenas=0
NettyByteBufPool.pageSize=4096
#unit is g
NettyByteBufPool.directMemorySize=4

#Netty Connection params
NettyNioEventLoop.ioThreadCount=25
NettyNioEventLoop.fastIOThreadCount=100
NettyNioEventLoop.slowIOThreadCount=8
NettyConnection.readTimeout=300000
NettyConnection.connectionTimeout=2000
NettyConnectionPool.acquireConnectionTimeout=1000
NettyConnectionPool.maxPendingAcquires=2000
NettyConnectionPool.maxConnections=4000
NettyConnectionPool.topAppMaxConnections=2000


#Netty Server site session params config
Server.port=10102
Server.sslPort=443
Server.backlog=10240
Server.maxSession=100000
Server.sessionTimeout=120000
Server.maxKeepAliveRequests=10240
Server.acceptThreadCnt=2
Server.serverIOThreadCnt=50
Server.acceptQueueSize=1000
Server.priorityQueueSize=500
Server.backupQueueSize=500
Server.workerThreadCoreSize=100
Server.workerThreadMaxSize=200
Server.priorityHandlers=100
Server.backupHandlers=20
#Server session idle timeout unit is ms
Server.sessionIdleTime=300000
Server.maxContentLength=512

#masla async push thread pool params
masla.push.thread.pool.core.size=50
masla.push.thread.pool.core.maxsize=100
masla.push.thread.pool.core.queuesize=1000
MaslaProcessorThreadCount.processorCount=10

#masla gray request thread pool params
masla.gray.request.thread.pool.core.size=2
masla.gray.request.thread.pool.core.maxsize=10
masla.gray.request.thread.pool.core.queuesize=300

masla.servlet.context.default.timeout.pending=120000

masla.inner.enable=true
masla.group.all=true
masla.producer.name=masla-test

masla.admin.server.address=192.168.3.52:8082

masla.group.internation=false