masla.gateway.routes.service.test1.name=test1
masla.gateway.routes.service.test1.pattern=^/test/*
masla.gateway.routes.service.test1.direct=/direct/xx/request
masla.gateway.routes.service.test1.rewrite=/${0}/test/xx
masla.gateway.routes.service.test1.domain=www.test1.com
masla.gateway.routes.service.test1.timeout=1000

#service level black filter
masla.gateway.routes.service.test1.filter.black.path=/test/xxx/sss
masla.gateway.routes.service.test1.filter.black.ip=192.168.10.1
masla.gateway.routes.service.test1.filter.black.queryString.key=RR
masla.gateway.routes.service.test1.filter.black.queryString.value=RR
masla.gateway.routes.service.test1.filter.black.header.key=RR
masla.gateway.routes.service.test1.filter.black.header.value=RR

#service level flowlimit
masla.gateway.routes.service.test1.filter.flowLimit.path=/test/xxx/sss
masla.gateway.routes.service.test1.filter.flowLimit.maxfreq=1000
masla.gateway.routes.service.test1.filter.flowLimit.interval=2

#global black filter
masla.gateway.routes.filter.black.path=/test/xxx/sss
masla.gateway.routes.filter.black.ip=192.168.10.1
masla.gateway.routes.filter.black.queryString.key=RR
masla.gateway.routes.filter.black.queryString.value=RR
masla.gateway.routes.filter.black.header.key=RR
masla.gateway.routes.filter.black.header.value=RR


masla.gateway.routes.service.demo1.name=demo1
masla.gateway.routes.service.demo1.pattern=^/demo1/*
masla.gateway.routes.service.demo1.domain=www.demo.com
masla.gateway.routes.service.demo1.timeout=1000
masla.gateway.routes.service.demo1.lb=RR
masla.gateway.routes.service.demo1.limit

