/**
 *
 */
package com.msw.masla.protocol.http.netty.event;


/**
 * Created by Gavin.peng on 2017/6/5.
 */
public enum EventState {
    DISPATCHING, REQUESTING, REQUEST_COMPLETE, REQUEST_FAILED, RESPONSE_HEAD,
    RESPONSE_RECEIVE_EXCEPTION, RESPONSE_COMPLETE, RESPONSE_FAILED,
    PUSH_INIT, PUSHING, PUSH_SUCCESS_REQUEST_COMPLETE, PUSH_SUCCESS_REQUEST_FAILED, PUSH_FAILED
}
